build: Checker.java Main.java
	javac Checker.java Main.java -classpath json-simple-1.1.1.jar

buildlibra:
	cd /home/user/Desktop/java/json-simple && ant
	cp /home/user/Desktop/java/json-simple/target/json-simple-1.1.1.jar .
	cp /home/user/Desktop/java/json-simple/target/classes/org/json/simple/parser/* .
